imennik =  input("Для гри ( Mad Libs ) Назви будь-який іменник!\n")
kolir = input ("Назви будь-який колір \n")
dieslovo = input ("Назви будь-яке дієслово\n")
namepets = input ("Назви будь-яку назву тварини\n")
nameplace = input ("Назви будь-яку назва місця\n")
print(f'Одного разу {imennik} був дуже сумний, тому що він був {kolir}. Він вирішив {dieslovo} у {nameplace}, де зустрів {namepets}. Разом вони вирішили залишитися в {nameplace} назавжди, і стали найкращими друзями.\n')